### ISSUE TITLE
Possible Bug: Negative Probability with default config in cleanup

### ISSUE THREAD

**Issue by AsadJeewa** [google-deepmind/meltingpot#174]
In https://github.com/google-deepmind/meltingpot/blob/main/meltingpot/lua/levels/clean_up/components.lua#L64 the probability is negative due to the interpolation calculation so apples never spawn.

**Comment by AsadJeewa** [comment]
I guess technically apples would never grow so it still serves its purpose

**Comment by duenez** [comment]
Yes, that's the idea.
