### ISSUE TITLE
Why `python_requires>=3.10`? 

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [google-deepmind/meltingpot#181]
Hi, is there a particular reason you only support >=3.10?
What is the limiting factor for lower versions?

Thanks, mark

**Comment by duenez** [comment]
We cannot test 3.9 or below internally, so we don't have a way to ensure compatibility anymore. You are free to try it on your side, but you'd have to build from source.

**Comment by pseudo-rnd-thoughts** [comment]
Fair, thanks for answering quickly
