### ISSUE TITLE
Environment with more social interactions

### ISSUE THREAD

**Issue by wenqian-ye** [google-deepmind/meltingpot#198]
Dear developer team,

Thank you very much for the effort to maintain this wonderful repository. It is very useful for social AI research. I am wondering if there exists a single environment that can contain all kinds of social interactions. such as cooperation, conflict, competition, coercion, and exchange).

**Comment by duenez** [comment]
Hello, there is a matrix with the aspects we think each substrate has in the Melting Pot 2.0 tech report: https://arxiv.org/pdf/2211.13746 Figure 2

Closing. Feel free to re-open if you have more questions.
