### ISSUE TITLE
evaluate library is missing

### ISSUE THREAD

**Issue by MiladInk** [google-deepmind/meltingpot#200]
Hi All! Thanks for the great repository. 
I wanted to point out that the link in the readme file pointing to the evaluation script is broken and I cannot find how to evaluate a saved model. Would you mind checking this out?

**Comment by duenez** [comment]
Thanks! I'm updating the link to point to the right place: https://github.com/google-deepmind/meltingpot/blob/main/meltingpot/utils/evaluation/evaluation.py
