### ISSUE TITLE
new pip release with chex fix

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [google-deepmind/meltingpot#221]
Could you make a new meltingpot release, 2.2.1 with the [chex version requirement removal](https://github.com/google-deepmind/meltingpot/commit/3019726e6d1ce203ac7c0229360df2e8ae3a8296), thanks

**Comment by jagapiou** [comment]
Fixed in v2.2.1

**Comment by pseudo-rnd-thoughts** [comment]
Thanks, much apprepriated
