### ISSUE TITLE
Guidance for Creating Avatars with Different Goals

### ISSUE THREAD

**Issue by AaronBabu** [google-deepmind/meltingpot#245]
Forgive me for the beginner question as I am still pretty new to MeltingPot in general. My aim is to create two agents that have their own respective targets that they have to reach. Currently, it seems that all agents copy one specific avatar to move towards the same goal, thus the possible actions of every agent are also the same. How do I set up agents such that each agent has a different goal and maybe even different actions than other agents? Is this possible?

As a very simple example, I would like to take the harvest tutorial game, make some of the apples red, initialize two agents, and have one agent collect red apples while the other collects green.

**Comment by duenez** [comment]
Closing. Feel free to re-open if you have more questions.
