### ISSUE TITLE
Scenarios clean_up_20 and territory__rooms_6 are wrong

### ISSUE THREAD

**Issue by duenez** [google-deepmind/meltingpot#246]
Two scenarios used for the Melting Pot Competition have issues:

* `clean_up_20` is using the wrong (puppet) bot: `clean_up__puppet_sanctioning_alternator_nice_0` instead of `clean_up__puppet_sanctioning_alternator_0`.
* `territory__rooms_6` is identical to `territory__rooms_5`.

The effective outcome is that the weight given to `territory__rooms_5` and `clean_up_19` are doubled.

**Comment by duenez** [comment]
At head, `clean_up_20` has been fixed. The tagged version 2.3.0 contains the mistake so it can be used to reproduce the state for the Melting Pot Competition 2023.

**Comment by jagapiou** [comment]
Fixed and will be released in v2.4
