### ISSUE TITLE
Qustion about Episode Length Settings in Evaluation Scenarios

### ISSUE THREAD

**Issue by az2181036** [google-deepmind/meltingpot#254]
Hello,

Firstly, I’d like to express my appreciation for your fantastic work on this gym. It’s been incredibly helpful and insightful.

I have a question regarding the evaluation scenarios: Given that the substrate can have a random length for an episode, are the episode lengths in the evaluation scenario also randomized? Additionally, how do you ensure that the evaluation of different algorithms is conducted under fair and consistent conditions concerning episode length?

Thank you for your assistance.

**Comment by duenez** [comment]
Yes, the episode lengths are also randomised. We just evaluate for many episodes and take average. It's important that the evaluation is _not_ on a finite horizon, because backwards induction is then possible, which changes the dynamics.
